// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:quran/modules/quran/data/models/m_bookmark.dart';
import 'package:quran/modules/quran/data/models/m_download_task.dart';
import 'package:quran/modules/quran/data/models/m_last_read.dart';
import 'package:quran/modules/quran/data/models/m_reciter_pref.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MBookmarkAdapter());
    registerAdapter(MDownloadTaskAdapter());
    registerAdapter(MLastReadAdapter());
    registerAdapter(MReciterPrefAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MBookmarkAdapter());
    registerAdapter(MDownloadTaskAdapter());
    registerAdapter(MLastReadAdapter());
    registerAdapter(MReciterPrefAdapter());
  }
}
